baseURL  =  "https://jamxe.com"
languageCode = "en"
DefaultContentLanguage = "en"
title  =  "Untitled Notes"
subtitle = ">$ cd /home/ "

theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5

[permalinks]
  posts = "/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
	name="阅读"
	url="/books/"
	weight="1"
  [[menu.main]]
  name="相册"
  url="/photos/"
  weight="2"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="3"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="4"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/jamxe'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.valine]
	enable = true
    appId = '7l7br39sXcMmtbhhkFArzaJ0-MdYXbMMI'
    appKey = 'IiScllic2NNmtvbq2BsOgqr8'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true
    serverURLs = "https://powerxe.avosapps.us/"

[params.twikoo]
	enable = true